version: '3.8'

services:
  backend:
    build:
      context: .
      target: builder
    container_name: green_park_dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    command: npm run dev
    depends_on:
      - db
  
  db:
    image: mysql:8.0.21
    container_name: green_park_db_dev
    ports:
      - 4001:3306
    restart: always
    environment:
      MYSQL_USER_FILE: green_park
      MYSQL_PASSWORD_FILE: my_secret_passw
      MYSQL_ROOT_PASSWORD_FILE: my_secret_root_passw

networks:
  default:
    name: green_park_network