version: '3.8'

services:
  backend:
    build:
      context: .
      target: builder
    container_name: green_park_dev
    volumes:
      - ./:/usr/src/app
    ports:
      - 4000:4000
    command: npm run dev
    depends_on:
      - db
  
  db:
    image: mysql:8.0.21
    container_name: green_park_db_dev
    ports:
      - 4001:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_root_passw
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

networks:
  default:
    name: green_park_network