version: '3.8'

services:
  backend:
    build:
      context: .
      target: builder
    container_name: green_park_dev
    volumes:
      - ./:/usr/src/app
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    command: npm run dev
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: mysql:8.0.21
    container_name: green_park_db_dev
    ports:
      - ${MYSQL_EXT_PORT}:3306
    restart: always
    env_file:
      - .env
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

networks:
  default:
    name: green_park_network
